# 🚗 Road Accident Analysis — Exploratory Data Analysis

### UK Road Safety Collision Data — 2025

**Project Type:** Exploratory Data Analysis (EDA)  
**Dataset:** Road Safety Data - Collisions - 2025  
**Source:** UK Department for Transport (DfT)

---

### Project Objective

The objective of this project is to perform a comprehensive Exploratory Data Analysis
of road collision data to identify patterns, trends, relationships, and factors
associated with road accidents and collision severity.

The analysis will examine accident characteristics including:

- Collision severity
- Date and time
- Road type
- Speed limit
- Junction characteristics
- Weather conditions
- Road surface conditions
- Light conditions
- Number of vehicles
- Number of casualties
- Urban and rural areas
- Geographic location
- Special road and environmental conditions

## 1. Business Problem

Road collisions are influenced by multiple factors such as road conditions,
weather, lighting, speed limits, road type, junction characteristics, and
the time at which a collision occurs.

Analyzing these factors can help identify patterns associated with accident
frequency and severity.

The purpose of this project is to explore road collision data and identify
important patterns, relationships, and risk factors that can support
data-driven road safety analysis.

## 2. Project Objectives

The main objectives of this project are:

1. Understand the structure and characteristics of the dataset.
2. Examine the quality and completeness of the raw data.
3. Identify missing values and duplicate records.
4. Understand the data types of all variables.
5. Identify categorical, numerical, date, time, and geographic variables.
6. Investigate unusual or potentially invalid values.
7. Analyze the distribution of collision-related variables.
8. Explore relationships between road, environmental, and collision factors.
9. Analyze accident patterns across different time periods.
10. Investigate factors associated with collision severity.
11. Generate meaningful analytical insights.
12. Develop data-driven conclusions and recommendations.

## 3. Dataset Information

The dataset contains road collision records collected through the UK's
STATS19 road accident reporting system.

### Dataset Details

| Attribute | Description |
|---|---|
| Country | United Kingdom |
| Year | 2025 |
| Dataset Type | Collision-level data |
| Source | UK Department for Transport |
| File | `collisions_2025.csv` |
| Records | Collision-level observations |
| Variables | 44 |

The dataset contains information about collision circumstances, location,
road characteristics, environmental conditions, vehicles, casualties,
and collision severity.

> Note: Several variables are represented using coded values. These codes
> will be interpreted using the official DfT data documentation rather than
> making assumptions about their meaning.

In [1]:
# Import required libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Libraries imported successfully!")

Libraries imported successfully!

In [2]:
# Load the raw collision dataset

df = pd.read_csv("../01_Raw_Data/collisions_2025.csv")

print("Dataset loaded successfully!")

Dataset loaded successfully!

In [3]:
# Verify Dataset
df

,collision_index,collision_year,collision_ref_no,location_easting_osgr,location_northing_osgr,longitude,latitude,police_force,collision_severity,number_of_vehicles,...,carriageway_hazards_historic,carriageway_hazards,urban_or_rural_area,did_police_officer_attend_scene_of_accident,trunk_road_flag,lsoa_of_accident_location,enhanced_severity_collision,collision_injury_based,collision_adjusted_severity_serious,collision_adjusted_severity_slight
0,202517H102225,2025,17H102225,449216.0,534979.0,-1.23770,54.70743,17,2,3,...,-1,0,2,1,2,E01033467,7,1,1.00000,0.00000
1,2025070815222,2025,070815222,363808.0,389192.0,-2.54576,53.39831,7,3,2,...,-1,0,1,2,2,E01012556,3,1,0.00000,1.00000
2,2025070937984,2025,070937984,362413.0,389071.0,-2.56673,53.39712,7,2,2,...,-1,0,1,3,2,E01012478,7,1,1.00000,0.00000
3,2025041687395,2025,041687395,368238.0,427802.0,-2.48308,53.74562,4,2,1,...,-1,0,1,1,2,E01012655,7,1,1.00000,0.00000
4,2025161555094,2025,161555094,510792.0,432167.0,-0.32035,53.77406,16,3,2,...,-1,0,1,1,2,E01012815,3,1,0.00000,1.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101520,2025622500238,2025,622500238,309591.0,179600.0,-3.30409,51.50807,62,3,2,...,0,13,2,1,-1,W01001729,-1,0,0.19717,0.80283
101521,2025622500335,2025,622500335,316017.0,181049.0,-3.21187,51.52209,62,3,2,...,0,0,1,1,-1,W01001851,-1,0,0.10476,0.89524
101522,2025610038025,2025,610038025,315454.0,186626.0,-3.22133,51.57214,61,3,1,...,0,0,1,1,-1,W01001424,-1,0,0.17878,0.82122
101523,2025610009425,2025,610009425,353274.0,193789.0,-2.67663,51.64095,61,3,1,...,0,0,1,1,-1,W01001587,-1,0,0.15929,0.84071
101524,2025631632945,2025,631632945,309912.0,313706.0,-3.33500,52.71349,63,3,2,...,-1,0,2,1,-1,W01000475,3,1,0.00000,1.00000

In [4]:
# Verify all dataset columns

print("Total columns in dataset:", len(df.columns))

for i, column in enumerate(df.columns, start=1):
    print(f"{i:02d}. {column}")

Total columns in dataset: 44
01. collision_index
02. collision_year
03. collision_ref_no
04. location_easting_osgr
05. location_northing_osgr
06. longitude
07. latitude
08. police_force
09. collision_severity
10. number_of_vehicles
11. number_of_casualties
12. date
13. day_of_week
14. time
15. local_authority_district
16. local_authority_ons_district
17. local_authority_highway
18. local_authority_highway_current
19. first_road_class
20. first_road_number
21. road_type
22. speed_limit
23. junction_detail_historic
24. junction_detail
25. junction_control
26. second_road_class
27. second_road_number
28. pedestrian_crossing_human_control_historic
29. pedestrian_crossing_physical_facilities_historic
30. pedestrian_crossing
31. light_conditions
32. weather_conditions
33. road_surface_conditions
34. special_conditions_at_site
35. carriageway_hazards_historic
36. carriageway_hazards
37. urban_or_rural_area
38. did_police_officer_attend_scene_of_accident
39. trunk_road_flag
40. lsoa_of_accident_location
41. enhanced_severity_collision
42. collision_injury_based
43. collision_adjusted_severity_serious
44. collision_adjusted_severity_slight

In [5]:
# Display the First Five Records
df.head()

,collision_index,collision_year,collision_ref_no,location_easting_osgr,location_northing_osgr,longitude,latitude,police_force,collision_severity,number_of_vehicles,...,carriageway_hazards_historic,carriageway_hazards,urban_or_rural_area,did_police_officer_attend_scene_of_accident,trunk_road_flag,lsoa_of_accident_location,enhanced_severity_collision,collision_injury_based,collision_adjusted_severity_serious,collision_adjusted_severity_slight
0,202517H102225,2025,17H102225,449216.0,534979.0,-1.23770,54.70743,17,2,3,...,-1,0,2,1,2,E01033467,7,1,1.0,0.0
1,2025070815222,2025,070815222,363808.0,389192.0,-2.54576,53.39831,7,3,2,...,-1,0,1,2,2,E01012556,3,1,0.0,1.0
2,2025070937984,2025,070937984,362413.0,389071.0,-2.56673,53.39712,7,2,2,...,-1,0,1,3,2,E01012478,7,1,1.0,0.0
3,2025041687395,2025,041687395,368238.0,427802.0,-2.48308,53.74562,4,2,1,...,-1,0,1,1,2,E01012655,7,1,1.0,0.0
4,2025161555094,2025,161555094,510792.0,432167.0,-0.32035,53.77406,16,3,2,...,-1,0,1,1,2,E01012815,3,1,0.0,1.0

In [6]:
# Display the Last Five Records
df.tail()

,collision_index,collision_year,collision_ref_no,location_easting_osgr,location_northing_osgr,longitude,latitude,police_force,collision_severity,number_of_vehicles,...,carriageway_hazards_historic,carriageway_hazards,urban_or_rural_area,did_police_officer_attend_scene_of_accident,trunk_road_flag,lsoa_of_accident_location,enhanced_severity_collision,collision_injury_based,collision_adjusted_severity_serious,collision_adjusted_severity_slight
101520,2025622500238,2025,622500238,309591.0,179600.0,-3.30409,51.50807,62,3,2,...,0,13,2,1,-1,W01001729,-1,0,0.19717,0.80283
101521,2025622500335,2025,622500335,316017.0,181049.0,-3.21187,51.52209,62,3,2,...,0,0,1,1,-1,W01001851,-1,0,0.10476,0.89524
101522,2025610038025,2025,610038025,315454.0,186626.0,-3.22133,51.57214,61,3,1,...,0,0,1,1,-1,W01001424,-1,0,0.17878,0.82122
101523,2025610009425,2025,610009425,353274.0,193789.0,-2.67663,51.64095,61,3,1,...,0,0,1,1,-1,W01001587,-1,0,0.15929,0.84071
101524,2025631632945,2025,631632945,309912.0,313706.0,-3.33500,52.71349,63,3,2,...,-1,0,2,1,-1,W01000475,3,1,0.00000,1.00000

In [7]:
df.sample(10, random_state=42)  # Random Sampling

,collision_index,collision_year,collision_ref_no,location_easting_osgr,location_northing_osgr,longitude,latitude,police_force,collision_severity,number_of_vehicles,...,carriageway_hazards_historic,carriageway_hazards,urban_or_rural_area,did_police_officer_attend_scene_of_accident,trunk_road_flag,lsoa_of_accident_location,enhanced_severity_collision,collision_injury_based,collision_adjusted_severity_serious,collision_adjusted_severity_slight
31755,2025010582873,2025,010582873,536140.0,173297.0,-0.04252,51.44231,1,2,2,...,-1,0,1,1,2,E01003229,7,1,1.00000,0.00000
55521,2025201644001,2025,201644001,435222.0,279582.0,-1.48360,52.41311,20,3,1,...,-1,0,1,1,2,E01009659,3,1,0.00000,1.00000
27622,2025031585958,2025,031585958,352527.0,479268.0,-2.72933,54.20694,3,3,1,...,-1,0,2,1,2,E01019347,3,1,0.00000,1.00000
61910,2025430653173,2025,430653173,486606.0,207602.0,-0.74655,51.76042,43,3,1,...,-1,0,2,1,2,E01017727,3,1,0.00000,1.00000
63482,2025161617200,2025,161617200,489610.0,430714.0,-0.64207,53.76508,16,3,2,...,-1,0,2,1,1,E01012969,3,1,0.00000,1.00000
62159,2025320230593,2025,320230593,518747.0,308190.0,-0.24581,52.65844,32,3,1,...,0,0,2,1,2,E01026304,-1,0,0.10189,0.89811
77781,2025201578594,2025,201578594,411942.0,294754.0,-1.82531,52.55050,20,2,1,...,-1,0,1,2,2,E01009471,7,1,1.00000,0.00000
22726,2025221568631,2025,221568631,405009.0,264886.0,-1.92800,52.28210,22,3,2,...,-1,0,2,3,2,E01032256,3,1,0.00000,1.00000
51958,2025461613116,2025,461613116,558635.0,173014.0,0.28077,51.43392,46,3,2,...,-1,0,2,1,2,E01035280,3,1,0.00000,1.00000
62273,2025543100325,2025,543100325,414804.0,187195.0,-1.78774,51.58342,54,3,1,...,0,0,1,1,2,E01015527,-1,0,0.05894,0.94106

In [8]:
# Dataset Dimensions
print(f"Number of records: {df.shape[0]:,}")
print(f"Number of variables: {df.shape[1]}")

Number of records: 101,525
Number of variables: 44

In [9]:
# Dataset Size

print(f"The dataset contains {df.shape[0]:,} collision records and {df.shape[1]} variables.")

The dataset contains 101,525 collision records and 44 variables.

In [10]:
# Columns Name
df.columns

Index(['collision_index', 'collision_year', 'collision_ref_no',
       'location_easting_osgr', 'location_northing_osgr', 'longitude',
       'latitude', 'police_force', 'collision_severity', 'number_of_vehicles',
       'number_of_casualties', 'date', 'day_of_week', 'time',
       'local_authority_district', 'local_authority_ons_district',
       'local_authority_highway', 'local_authority_highway_current',
       'first_road_class', 'first_road_number', 'road_type', 'speed_limit',
       'junction_detail_historic', 'junction_detail', 'junction_control',
       'second_road_class', 'second_road_number',
       'pedestrian_crossing_human_control_historic',
       'pedestrian_crossing_physical_facilities_historic',
       'pedestrian_crossing', 'light_conditions', 'weather_conditions',
       'road_surface_conditions', 'special_conditions_at_site',
       'carriageway_hazards_historic', 'carriageway_hazards',
       'urban_or_rural_area', 'did_police_officer_attend_scene_of_accident',
       'trunk_road_flag', 'lsoa_of_accident_location',
       'enhanced_severity_collision', 'collision_injury_based',
       'collision_adjusted_severity_serious',
       'collision_adjusted_severity_slight'],
      dtype='str')

In [11]:
# Columns Name as List
list(df.columns)

['collision_index',
 'collision_year',
 'collision_ref_no',
 'location_easting_osgr',
 'location_northing_osgr',
 'longitude',
 'latitude',
 'police_force',
 'collision_severity',
 'number_of_vehicles',
 'number_of_casualties',
 'date',
 'day_of_week',
 'time',
 'local_authority_district',
 'local_authority_ons_district',
 'local_authority_highway',
 'local_authority_highway_current',
 'first_road_class',
 'first_road_number',
 'road_type',
 'speed_limit',
 'junction_detail_historic',
 'junction_detail',
 'junction_control',
 'second_road_class',
 'second_road_number',
 'pedestrian_crossing_human_control_historic',
 'pedestrian_crossing_physical_facilities_historic',
 'pedestrian_crossing',
 'light_conditions',
 'weather_conditions',
 'road_surface_conditions',
 'special_conditions_at_site',
 'carriageway_hazards_historic',
 'carriageway_hazards',
 'urban_or_rural_area',
 'did_police_officer_attend_scene_of_accident',
 'trunk_road_flag',
 'lsoa_of_accident_location',
 'enhanced_severity_collision',
 'collision_injury_based',
 'collision_adjusted_severity_serious',
 'collision_adjusted_severity_slight']

In [12]:
# Dataset Information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 101525 entries, 0 to 101524
Data columns (total 44 columns):
 #   Column                                            Non-Null Count   Dtype
---  ------                                            --------------   -----
 0   collision_index                                   101525 non-null  str
 1   collision_year                                    101525 non-null  int64
 2   collision_ref_no                                  101525 non-null  str
 3   location_easting_osgr                             101523 non-null  float64
 4   location_northing_osgr                            101523 non-null  float64
 5   longitude                                         101523 non-null  float64
 6   latitude                                          101523 non-null  float64
 7   police_force                                      101525 non-null  int64
 8   collision_severity                                101525 non-null  int64
 9   number_of_vehicles                                101525 non-null  int64
 10  number_of_casualties                              101525 non-null  int64
 11  date                                              101525 non-null  str
 12  day_of_week                                       101525 non-null  int64
 13  time                                              101525 non-null  str
 14  local_authority_district                          101525 non-null  int64
 15  local_authority_ons_district                      101525 non-null  str
 16  local_authority_highway                           101525 non-null  str
 17  local_authority_highway_current                   101525 non-null  str
 18  first_road_class                                  101525 non-null  int64
 19  first_road_number                                 101525 non-null  int64
 20  road_type                                         101525 non-null  int64
 21  speed_limit                                       101525 non-null  int64
 22  junction_detail_historic                          101525 non-null  int64
 23  junction_detail                                   101525 non-null  int64
 24  junction_control                                  101525 non-null  int64
 25  second_road_class                                 101525 non-null  int64
 26  second_road_number                                101525 non-null  int64
 27  pedestrian_crossing_human_control_historic        101525 non-null  int64
 28  pedestrian_crossing_physical_facilities_historic  101525 non-null  int64
 29  pedestrian_crossing                               101525 non-null  int64
 30  light_conditions                                  101525 non-null  int64
 31  weather_conditions                                101525 non-null  int64
 32  road_surface_conditions                           101525 non-null  int64
 33  special_conditions_at_site                        101525 non-null  int64
 34  carriageway_hazards_historic                      101525 non-null  int64
 35  carriageway_hazards                               101525 non-null  int64
 36  urban_or_rural_area                               101525 non-null  int64
 37  did_police_officer_attend_scene_of_accident       101525 non-null  int64
 38  trunk_road_flag                                   101525 non-null  int64
 39  lsoa_of_accident_location                         101525 non-null  str
 40  enhanced_severity_collision                       101525 non-null  int64
 41  collision_injury_based                            101525 non-null  int64
 42  collision_adjusted_severity_serious               101525 non-null  float64
 43  collision_adjusted_severity_slight                101525 non-null  float64
dtypes: float64(6), int64(30), str(8)
memory usage: 34.1 MB

In [13]:
# Data Type
df.dtypes

collision_index                                         str
collision_year                                        int64
collision_ref_no                                        str
location_easting_osgr                               float64
location_northing_osgr                              float64
longitude                                           float64
latitude                                            float64
police_force                                          int64
collision_severity                                    int64
number_of_vehicles                                    int64
number_of_casualties                                  int64
date                                                    str
day_of_week                                           int64
time                                                    str
local_authority_district                              int64
local_authority_ons_district                            str
local_authority_highway                                 str
local_authority_highway_current                         str
first_road_class                                      int64
first_road_number                                     int64
road_type                                             int64
speed_limit                                           int64
junction_detail_historic                              int64
junction_detail                                       int64
junction_control                                      int64
second_road_class                                     int64
second_road_number                                    int64
pedestrian_crossing_human_control_historic            int64
pedestrian_crossing_physical_facilities_historic      int64
pedestrian_crossing                                   int64
light_conditions                                      int64
weather_conditions                                    int64
road_surface_conditions                               int64
special_conditions_at_site                            int64
carriageway_hazards_historic                          int64
carriageway_hazards                                   int64
urban_or_rural_area                                   int64
did_police_officer_attend_scene_of_accident           int64
trunk_road_flag                                       int64
lsoa_of_accident_location                               str
enhanced_severity_collision                           int64
collision_injury_based                                int64
collision_adjusted_severity_serious                 float64
collision_adjusted_severity_slight                  float64
dtype: object

In [14]:
# Data Type Summary
df.dtypes.value_counts()

int64      30
str         8
float64     6
Name: count, dtype: int64

In [15]:
# Numerical Columns
numerical_columns = df.select_dtypes(include=np.number).columns

print("Number of numerical columns:", len(numerical_columns))
print("\nNumerical columns:")
print(list(numerical_columns))

Number of numerical columns: 36

Numerical columns:
['collision_year', 'location_easting_osgr', 'location_northing_osgr', 'longitude', 'latitude', 'police_force', 'collision_severity', 'number_of_vehicles', 'number_of_casualties', 'day_of_week', 'local_authority_district', 'first_road_class', 'first_road_number', 'road_type', 'speed_limit', 'junction_detail_historic', 'junction_detail', 'junction_control', 'second_road_class', 'second_road_number', 'pedestrian_crossing_human_control_historic', 'pedestrian_crossing_physical_facilities_historic', 'pedestrian_crossing', 'light_conditions', 'weather_conditions', 'road_surface_conditions', 'special_conditions_at_site', 'carriageway_hazards_historic', 'carriageway_hazards', 'urban_or_rural_area', 'did_police_officer_attend_scene_of_accident', 'trunk_road_flag', 'enhanced_severity_collision', 'collision_injury_based', 'collision_adjusted_severity_serious', 'collision_adjusted_severity_slight']

In [16]:
# Categoryical Columns
categorical_columns = df.select_dtypes(include="object").columns

print("Number of categorical columns:", len(categorical_columns))
print("\nCategorical columns:")
print(list(categorical_columns))

Number of categorical columns: 8

Categorical columns:
['collision_index', 'collision_ref_no', 'date', 'time', 'local_authority_ons_district', 'local_authority_highway', 'local_authority_highway_current', 'lsoa_of_accident_location']

C:\Users\Shiva\AppData\Local\Temp\ipykernel_6720\2874826972.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(include="object").columns

In [17]:
# Missing Values
missing_values = df.isnull().sum()
missing_values

collision_index                                     0
collision_year                                      0
collision_ref_no                                    0
location_easting_osgr                               2
location_northing_osgr                              2
longitude                                           2
latitude                                            2
police_force                                        0
collision_severity                                  0
number_of_vehicles                                  0
number_of_casualties                                0
date                                                0
day_of_week                                         0
time                                                0
local_authority_district                            0
local_authority_ons_district                        0
local_authority_highway                             0
local_authority_highway_current                     0
first_road_class                                    0
first_road_number                                   0
road_type                                           0
speed_limit                                         0
junction_detail_historic                            0
junction_detail                                     0
junction_control                                    0
second_road_class                                   0
second_road_number                                  0
pedestrian_crossing_human_control_historic          0
pedestrian_crossing_physical_facilities_historic    0
pedestrian_crossing                                 0
light_conditions                                    0
weather_conditions                                  0
road_surface_conditions                             0
special_conditions_at_site                          0
carriageway_hazards_historic                        0
carriageway_hazards                                 0
urban_or_rural_area                                 0
did_police_officer_attend_scene_of_accident         0
trunk_road_flag                                     0
lsoa_of_accident_location                           0
enhanced_severity_collision                         0
collision_injury_based                              0
collision_adjusted_severity_serious                 0
collision_adjusted_severity_slight                  0
dtype: int64

In [18]:
# Missing Value Summary

missing_summary = pd.DataFrame({
    "Missing_Count": df.isnull().sum(),
    "Missing_Percentage": (df.isnull().mean() * 100).round(2)
})

missing_summary.sort_values(
    by="Missing_Percentage",
    ascending=False
)

,Missing_Count,Missing_Percentage
collision_index,0,0.0
collision_year,0,0.0
collision_ref_no,0,0.0
location_easting_osgr,2,0.0
location_northing_osgr,2,0.0
longitude,2,0.0
latitude,2,0.0
police_force,0,0.0
collision_severity,0,0.0
number_of_vehicles,0,0.0
number_of_casualties,0,0.0
date,0,0.0
day_of_week,0,0.0
time,0,0.0
local_authority_district,0,0.0
local_authority_ons_district,0,0.0
local_authority_highway,0,0.0
local_authority_highway_current,0,0.0
first_road_class,0,0.0
first_road_number,0,0.0
road_type,0,0.0
speed_limit,0,0.0
junction_detail_historic,0,0.0
junction_detail,0,0.0
junction_control,0,0.0
second_road_class,0,0.0
second_road_number,0,0.0
pedestrian_crossing_human_control_historic,0,0.0
pedestrian_crossing_physical_facilities_historic,0,0.0
pedestrian_crossing,0,0.0
light_conditions,0,0.0
weather_conditions,0,0.0
road_surface_conditions,0,0.0
special_conditions_at_site,0,0.0
carriageway_hazards_historic,0,0.0
carriageway_hazards,0,0.0
urban_or_rural_area,0,0.0
did_police_officer_attend_scene_of_accident,0,0.0
trunk_road_flag,0,0.0
lsoa_of_accident_location,0,0.0
enhanced_severity_collision,0,0.0
collision_injury_based,0,0.0
collision_adjusted_severity_serious,0,0.0
collision_adjusted_severity_slight,0,0.0

In [19]:
# Total Missing Values
total_missing = df.isnull().sum().sum()

print("Total missing values:", total_missing)

Total missing values: 8

In [20]:
# Duplicate Records
duplicate_count = df.duplicated().sum()

print("Number of duplicate rows:", duplicate_count)

Number of duplicate rows: 0

In [21]:
# Unique Values
unique_values = df.nunique()
unique_values.sort_values()

collision_year                                           1
local_authority_district                                 1
collision_injury_based                                   2
collision_severity                                       3
trunk_road_flag                                          3
urban_or_rural_area                                      3
did_police_officer_attend_scene_of_accident              3
pedestrian_crossing_human_control_historic               5
road_type                                                6
junction_control                                         6
speed_limit                                              6
enhanced_severity_collision                              6
light_conditions                                         6
first_road_class                                         7
road_surface_conditions                                  7
day_of_week                                              7
junction_detail                                          8
carriageway_hazards_historic                             8
pedestrian_crossing_physical_facilities_historic         8
second_road_class                                        9
weather_conditions                                       9
special_conditions_at_site                              10
pedestrian_crossing                                     10
junction_detail_historic                                11
number_of_vehicles                                      13
carriageway_hazards                                     14
number_of_casualties                                    21
police_force                                            44
local_authority_highway_current                        208
local_authority_highway                                208
local_authority_ons_district                           351
date                                                   365
time                                                  1440
second_road_number                                    2487
first_road_number                                     3110
collision_adjusted_severity_serious                   6557
collision_adjusted_severity_slight                    6557
lsoa_of_accident_location                            27179
latitude                                             82164
location_easting_osgr                                83236
location_northing_osgr                               83768
longitude                                            88044
collision_index                                     101525
collision_ref_no                                    101525
dtype: int64

In [22]:
# Unique Values Summary
unique_summary = pd.DataFrame({
    "Unique_Values": df.nunique(),
    "Data_Type": df.dtypes
})

unique_summary.sort_values(
    by="Unique_Values"
)

                                                  Unique_Values Data_Type
collision_year                                                1     int64
local_authority_district                                      1     int64
collision_injury_based                                        2     int64
collision_severity                                            3     int64
trunk_road_flag                                               3     int64
urban_or_rural_area                                           3     int64
did_police_officer_attend_scene_of_accident                   3     int64
pedestrian_crossing_human_control_historic                    5     int64
road_type                                                     6     int64
junction_control                                              6     int64
speed_limit                                                   6     int64
enhanced_severity_collision                                   6     int64
light_conditions                                              6     int64
first_road_class                                              7     int64
road_surface_conditions                                       7     int64
day_of_week                                                   7     int64
junction_detail                                               8     int64
carriageway_hazards_historic                                  8     int64
pedestrian_crossing_physical_facilities_historic              8     int64
second_road_class                                             9     int64
weather_conditions                                            9     int64
special_conditions_at_site                                   10     int64
pedestrian_crossing                                          10     int64
junction_detail_historic                                     11     int64
number_of_vehicles                                           13     int64
carriageway_hazards                                          14     int64
number_of_casualties                                         21     int64
police_force                                                 44     int64
local_authority_highway_current                             208       str
local_authority_highway                                     208       str
local_authority_ons_district                                351       str
date                                                        365       str
time                                                       1440       str
second_road_number                                         2487     int64
first_road_number                                          3110     int64
collision_adjusted_severity_serious                        6557   float64
collision_adjusted_severity_slight                         6557   float64
lsoa_of_accident_location                                 27179       str
latitude                                                  82164   float64
location_easting_osgr                                     83236   float64
location_northing_osgr                                    83768   float64
longitude                                                 88044   float64
collision_index                                          101525       str
collision_ref_no                                         101525       str

In [23]:
# Statistical Summary
df.describe()

,collision_year,location_easting_osgr,location_northing_osgr,longitude,latitude,police_force,collision_severity,number_of_vehicles,number_of_casualties,day_of_week,...,special_conditions_at_site,carriageway_hazards_historic,carriageway_hazards,urban_or_rural_area,did_police_officer_attend_scene_of_accident,trunk_road_flag,enhanced_severity_collision,collision_injury_based,collision_adjusted_severity_serious,collision_adjusted_severity_slight
count,101525.0,101523.000000,1.015230e+05,101523.000000,101523.000000,101525.000000,101525.000000,101525.000000,101525.000000,101525.000000,...,101525.000000,101525.000000,101525.000000,101525.000000,101525.000000,101525.000000,101525.000000,101525.000000,101525.000000,101525.000000
mean,2025.0,454027.068812,2.764592e+05,-1.223959,52.375658,27.962522,2.723250,1.811849,1.259621,4.126097,...,-0.834652,-0.839399,1.265324,1.338646,1.523585,1.726461,3.191470,0.865284,0.253561,0.732127
std,0.0,92739.506456,1.452150e+05,1.356983,1.308239,24.075091,0.478315,0.689631,0.816679,1.926299,...,0.631565,0.598058,8.722224,0.473335,0.838330,0.786635,2.209339,0.341421,0.428807,0.436721
min,2025.0,71253.000000,1.023700e+04,-7.417720,49.912530,1.000000,1.000000,1.000000,1.000000,1.000000,...,-1.000000,-1.000000,-1.000000,1.000000,1.000000,-1.000000,-1.000000,0.000000,0.000000,0.000000
25%,2025.0,392107.500000,1.753650e+05,-2.118700,51.464460,5.000000,2.000000,1.000000,1.000000,2.000000,...,-1.000000,-1.000000,0.000000,1.000000,1.000000,2.000000,3.000000,1.000000,0.000000,0.000000
50%,2025.0,458353.000000,2.228290e+05,-1.138910,51.888640,23.000000,3.000000,2.000000,1.000000,4.000000,...,-1.000000,-1.000000,0.000000,1.000000,1.000000,2.000000,3.000000,1.000000,0.000000,1.000000
75%,2025.0,529150.500000,3.813935e+05,-0.137910,53.325860,45.000000,3.000000,2.000000,1.000000,6.000000,...,-1.000000,-1.000000,0.000000,2.000000,2.000000,2.000000,3.000000,1.000000,0.229840,1.000000
max,2025.0,655126.000000,1.162591e+06,1.755590,60.345250,99.000000,3.000000,17.000000,142.000000,7.000000,...,9.000000,9.000000,99.000000,3.000000,3.000000,2.000000,7.000000,1.000000,1.000000,1.000000

In [24]:
# All Variables Summary
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
collision_index,101525,101525,202517H102225,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
collision_year,101525.0,NaN,NaN,NaN,2025.0,0.0,2025.0,2025.0,2025.0,2025.0,2025.0
collision_ref_no,101525,101525,17H102225,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
location_easting_osgr,101523.0,NaN,NaN,NaN,454027.068812,92739.506456,71253.0,392107.5,458353.0,529150.5,655126.0
location_northing_osgr,101523.0,NaN,NaN,NaN,276459.222127,145214.997315,10237.0,175365.0,222829.0,381393.5,1162591.0
longitude,101523.0,NaN,NaN,NaN,-1.223959,1.356983,-7.41772,-2.1187,-1.13891,-0.13791,1.75559
latitude,101523.0,NaN,NaN,NaN,52.375658,1.308239,49.91253,51.46446,51.88864,53.32586,60.34525
police_force,101525.0,NaN,NaN,NaN,27.962522,24.075091,1.0,5.0,23.0,45.0,99.0
collision_severity,101525.0,NaN,NaN,NaN,2.72325,0.478315,1.0,2.0,3.0,3.0,3.0
number_of_vehicles,101525.0,NaN,NaN,NaN,1.811849,0.689631,1.0,1.0,2.0,2.0,17.0
number_of_casualties,101525.0,NaN,NaN,NaN,1.259621,0.816679,1.0,1.0,1.0,1.0,142.0
date,101525,365,19/12/2025,412,NaN,NaN,NaN,NaN,NaN,NaN,NaN
day_of_week,101525.0,NaN,NaN,NaN,4.126097,1.926299,1.0,2.0,4.0,6.0,7.0
time,101525,1440,17:00,891,NaN,NaN,NaN,NaN,NaN,NaN,NaN
local_authority_district,101525.0,NaN,NaN,NaN,-1.0,0.0,-1.0,-1.0,-1.0,-1.0,-1.0
local_authority_ons_district,101525,351,E08000025,2307,NaN,NaN,NaN,NaN,NaN,NaN,NaN
local_authority_highway,101525,208,E10000016,2957,NaN,NaN,NaN,NaN,NaN,NaN,NaN
local_authority_highway_current,101525,208,E10000016,2957,NaN,NaN,NaN,NaN,NaN,NaN,NaN
first_road_class,101525.0,NaN,NaN,NaN,4.245762,1.466336,-1.0,3.0,4.0,6.0,6.0
first_road_number,101525.0,NaN,NaN,NaN,796.149195,1592.749929,-1.0,0.0,30.0,556.0,9999.0
road_type,101525.0,NaN,NaN,NaN,5.212815,1.707555,1.0,6.0,6.0,6.0,9.0
speed_limit,101525.0,NaN,NaN,NaN,35.771189,14.6383,20.0,30.0,30.0,40.0,70.0
junction_detail_historic,101525.0,NaN,NaN,NaN,-0.291406,5.376669,-1.0,-1.0,-1.0,-1.0,99.0
junction_detail,101525.0,NaN,NaN,NaN,8.323861,13.209492,-1.0,0.0,0.0,13.0,99.0
junction_control,101525.0,NaN,NaN,NaN,1.756641,2.692095,-1.0,-1.0,2.0,4.0,9.0
second_road_class,101525.0,NaN,NaN,NaN,4.008776,2.532016,-1.0,1.0,6.0,6.0,9.0
second_road_number,101525.0,NaN,NaN,NaN,256.918168,1002.32017,-1.0,0.0,0.0,0.0,9998.0
pedestrian_crossing_human_control_historic,101525.0,NaN,NaN,NaN,-0.821364,0.758144,-1.0,-1.0,-1.0,-1.0,9.0
pedestrian_crossing_physical_facilities_historic,101525.0,NaN,NaN,NaN,-0.718591,1.123856,-1.0,-1.0,-1.0,-1.0,9.0
pedestrian_crossing,101525.0,NaN,NaN,NaN,3.097789,7.830814,-1.0,0.0,0.0,0.0,99.0
light_conditions,101525.0,NaN,NaN,NaN,2.013553,1.698397,-1.0,1.0,1.0,4.0,7.0
weather_conditions,101525.0,NaN,NaN,NaN,1.598769,1.783953,1.0,1.0,1.0,1.0,9.0
road_surface_conditions,101525.0,NaN,NaN,NaN,1.359114,1.05029,-1.0,1.0,1.0,1.0,9.0
special_conditions_at_site,101525.0,NaN,NaN,NaN,-0.834652,0.631565,-1.0,-1.0,-1.0,-1.0,9.0
carriageway_hazards_historic,101525.0,NaN,NaN,NaN,-0.839399,0.598058,-1.0,-1.0,-1.0,-1.0,9.0
carriageway_hazards,101525.0,NaN,NaN,NaN,1.265324,8.722224,-1.0,0.0,0.0,0.0,99.0
urban_or_rural_area,101525.0,NaN,NaN,NaN,1.338646,0.473335,1.0,1.0,1.0,2.0,3.0
did_police_officer_attend_scene_of_accident,101525.0,NaN,NaN,NaN,1.523585,0.83833,1.0,1.0,1.0,2.0,3.0
trunk_road_flag,101525.0,NaN,NaN,NaN,1.726461,0.786635,-1.0,2.0,2.0,2.0,2.0
lsoa_of_accident_location,101525,27179,-1,4107,NaN,NaN,NaN,NaN,NaN,NaN,NaN
enhanced_severity_collision,101525.0,NaN,NaN,NaN,3.19147,2.209339,-1.0,3.0,3.0,3.0,7.0
collision_injury_based,101525.0,NaN,NaN,NaN,0.865284,0.341421,0.0,1.0,1.0,1.0,1.0
collision_adjusted_severity_serious,101525.0,NaN,NaN,NaN,0.253561,0.428807,0.0,0.0,0.0,0.22984,1.0
collision_adjusted_severity_slight,101525.0,NaN,NaN,NaN,0.732127,0.436721,0.0,0.0,1.0,1.0,1.0

In [25]:
# Numerical Summary Transposed
df.describe().T

,count,mean,std,min,25%,50%,75%,max
collision_year,101525.0,2025.000000,0.000000,2025.00000,2025.00000,2025.00000,2025.00000,2.025000e+03
location_easting_osgr,101523.0,454027.068812,92739.506456,71253.00000,392107.50000,458353.00000,529150.50000,6.551260e+05
location_northing_osgr,101523.0,276459.222127,145214.997315,10237.00000,175365.00000,222829.00000,381393.50000,1.162591e+06
longitude,101523.0,-1.223959,1.356983,-7.41772,-2.11870,-1.13891,-0.13791,1.755590e+00
latitude,101523.0,52.375658,1.308239,49.91253,51.46446,51.88864,53.32586,6.034525e+01
police_force,101525.0,27.962522,24.075091,1.00000,5.00000,23.00000,45.00000,9.900000e+01
collision_severity,101525.0,2.723250,0.478315,1.00000,2.00000,3.00000,3.00000,3.000000e+00
number_of_vehicles,101525.0,1.811849,0.689631,1.00000,1.00000,2.00000,2.00000,1.700000e+01
number_of_casualties,101525.0,1.259621,0.816679,1.00000,1.00000,1.00000,1.00000,1.420000e+02
day_of_week,101525.0,4.126097,1.926299,1.00000,2.00000,4.00000,6.00000,7.000000e+00
local_authority_district,101525.0,-1.000000,0.000000,-1.00000,-1.00000,-1.00000,-1.00000,-1.000000e+00
first_road_class,101525.0,4.245762,1.466336,-1.00000,3.00000,4.00000,6.00000,6.000000e+00
first_road_number,101525.0,796.149195,1592.749929,-1.00000,0.00000,30.00000,556.00000,9.999000e+03
road_type,101525.0,5.212815,1.707555,1.00000,6.00000,6.00000,6.00000,9.000000e+00
speed_limit,101525.0,35.771189,14.638300,20.00000,30.00000,30.00000,40.00000,7.000000e+01
junction_detail_historic,101525.0,-0.291406,5.376669,-1.00000,-1.00000,-1.00000,-1.00000,9.900000e+01
junction_detail,101525.0,8.323861,13.209492,-1.00000,0.00000,0.00000,13.00000,9.900000e+01
junction_control,101525.0,1.756641,2.692095,-1.00000,-1.00000,2.00000,4.00000,9.000000e+00
second_road_class,101525.0,4.008776,2.532016,-1.00000,1.00000,6.00000,6.00000,9.000000e+00
second_road_number,101525.0,256.918168,1002.320170,-1.00000,0.00000,0.00000,0.00000,9.998000e+03
pedestrian_crossing_human_control_historic,101525.0,-0.821364,0.758144,-1.00000,-1.00000,-1.00000,-1.00000,9.000000e+00
pedestrian_crossing_physical_facilities_historic,101525.0,-0.718591,1.123856,-1.00000,-1.00000,-1.00000,-1.00000,9.000000e+00
pedestrian_crossing,101525.0,3.097789,7.830814,-1.00000,0.00000,0.00000,0.00000,9.900000e+01
light_conditions,101525.0,2.013553,1.698397,-1.00000,1.00000,1.00000,4.00000,7.000000e+00
weather_conditions,101525.0,1.598769,1.783953,1.00000,1.00000,1.00000,1.00000,9.000000e+00
road_surface_conditions,101525.0,1.359114,1.050290,-1.00000,1.00000,1.00000,1.00000,9.000000e+00
special_conditions_at_site,101525.0,-0.834652,0.631565,-1.00000,-1.00000,-1.00000,-1.00000,9.000000e+00
carriageway_hazards_historic,101525.0,-0.839399,0.598058,-1.00000,-1.00000,-1.00000,-1.00000,9.000000e+00
carriageway_hazards,101525.0,1.265324,8.722224,-1.00000,0.00000,0.00000,0.00000,9.900000e+01
urban_or_rural_area,101525.0,1.338646,0.473335,1.00000,1.00000,1.00000,2.00000,3.000000e+00
did_police_officer_attend_scene_of_accident,101525.0,1.523585,0.838330,1.00000,1.00000,1.00000,2.00000,3.000000e+00
trunk_road_flag,101525.0,1.726461,0.786635,-1.00000,2.00000,2.00000,2.00000,2.000000e+00
enhanced_severity_collision,101525.0,3.191470,2.209339,-1.00000,3.00000,3.00000,3.00000,7.000000e+00
collision_injury_based,101525.0,0.865284,0.341421,0.00000,1.00000,1.00000,1.00000,1.000000e+00
collision_adjusted_severity_serious,101525.0,0.253561,0.428807,0.00000,0.00000,0.00000,0.22984,1.000000e+00
collision_adjusted_severity_slight,101525.0,0.732127,0.436721,0.00000,0.00000,1.00000,1.00000,1.000000e+00

In [26]:
# Identify Date Column
print("Date column data type:", df["date"].dtype)
print("\nSample date values:")
print(df["date"].head())

Date column data type: str

Sample date values:
0    05/03/2025
1    03/10/2025
2    15/11/2025
3    23/12/2025
4    06/02/2025
Name: date, dtype: str

In [27]:
# Identify Time Column
print("Time column data type:", df["time"].dtype)
print("\nSample time values:")
print(df["time"].head())

Time column data type: str

Sample time values:
0    12:50
1    18:35
2    21:00
3    01:44
4    08:52
Name: time, dtype: str

In [28]:
# Check Collision Year
df["collision_year"].value_counts()

collision_year
2025    101525
Name: count, dtype: int64

In [29]:
# Collision Severity
df["collision_severity"].value_counts().sort_index()

collision_severity
1     1453
2    25191
3    74881
Name: count, dtype: int64

In [30]:
# Number of Vehicles
df["number_of_vehicles"].describe()

count    101525.000000
mean          1.811849
std           0.689631
min           1.000000
25%           1.000000
50%           2.000000
75%           2.000000
max          17.000000
Name: number_of_vehicles, dtype: float64

In [31]:
# Number of Casualties
df["number_of_casualties"].describe()

count    101525.000000
mean          1.259621
std           0.816679
min           1.000000
25%           1.000000
50%           1.000000
75%           1.000000
max         142.000000
Name: number_of_casualties, dtype: float64

In [32]:
# Speed Limit
df["speed_limit"].value_counts().sort_index()

speed_limit
20    20045
30    49673
40     8886
50     4612
60    12709
70     5600
Name: count, dtype: int64

In [33]:
# Road Type
df["road_type"].value_counts().sort_index()

road_type
1     6795
2     2398
3    14610
6    74150
7     1619
9     1953
Name: count, dtype: int64

In [34]:
# Weather Conditions
df["weather_conditions"].value_counts().sort_index()

weather_conditions
1    83405
2    10230
3      235
4      715
5      880
6       19
7      342
8     3314
9     2385
Name: count, dtype: int64

In [35]:
# Road Surface Conditions
df["road_surface_conditions"].value_counts().sort_index()

road_surface_conditions
-1      634
 1    75679
 2    22312
 3      146
 4     1261
 5      151
 9     1342
Name: count, dtype: int64

In [36]:
# Light Condition
df["light_conditions"].value_counts().sort_index()

light_conditions
-1       16
 1    72814
 4    20705
 5      720
 6     5682
 7     1588
Name: count, dtype: int64

In [37]:
# Day of Week
df["day_of_week"].value_counts().sort_index()

day_of_week
1    11197
2    14309
3    14880
4    15369
5    15304
6    16811
7    13655
Name: count, dtype: int64

In [38]:
# Geographic Information 
print("Latitude range:")
print(df["latitude"].min(), "to", df["latitude"].max())

print("\nLongitude range:")
print(df["longitude"].min(), "to", df["longitude"].max())

Latitude range:
49.91253 to 60.34525

Longitude range:
-7.41772 to 1.75559

In [39]:
# Columns-Wise Summary
column_summary = pd.DataFrame({
    "Column": df.columns,
    "Data_Type": df.dtypes.values,
    "Missing_Count": df.isnull().sum().values,
    "Missing_Percentage": (df.isnull().mean() * 100).round(2).values,
    "Unique_Values": df.nunique().values
})

column_summary

,Column,Data_Type,Missing_Count,Missing_Percentage,Unique_Values
0,collision_index,str,0,0.0,101525
1,collision_year,int64,0,0.0,1
2,collision_ref_no,str,0,0.0,101525
3,location_easting_osgr,float64,2,0.0,83236
4,location_northing_osgr,float64,2,0.0,83768
5,longitude,float64,2,0.0,88044
6,latitude,float64,2,0.0,82164
7,police_force,int64,0,0.0,44
8,collision_severity,int64,0,0.0,3
9,number_of_vehicles,int64,0,0.0,13
10,number_of_casualties,int64,0,0.0,21
11,date,str,0,0.0,365
12,day_of_week,int64,0,0.0,7
13,time,str,0,0.0,1440
14,local_authority_district,int64,0,0.0,1
15,local_authority_ons_district,str,0,0.0,351
16,local_authority_highway,str,0,0.0,208
17,local_authority_highway_current,str,0,0.0,208
18,first_road_class,int64,0,0.0,7
19,first_road_number,int64,0,0.0,3110
20,road_type,int64,0,0.0,6
21,speed_limit,int64,0,0.0,6
22,junction_detail_historic,int64,0,0.0,11
23,junction_detail,int64,0,0.0,8
24,junction_control,int64,0,0.0,6
25,second_road_class,int64,0,0.0,9
26,second_road_number,int64,0,0.0,2487
27,pedestrian_crossing_human_control_historic,int64,0,0.0,5
28,pedestrian_crossing_physical_facilities_historic,int64,0,0.0,8
29,pedestrian_crossing,int64,0,0.0,10
30,light_conditions,int64,0,0.0,6
31,weather_conditions,int64,0,0.0,9
32,road_surface_conditions,int64,0,0.0,7
33,special_conditions_at_site,int64,0,0.0,10
34,carriageway_hazards_historic,int64,0,0.0,8
35,carriageway_hazards,int64,0,0.0,14
36,urban_or_rural_area,int64,0,0.0,3
37,did_police_officer_attend_scene_of_accident,int64,0,0.0,3
38,trunk_road_flag,int64,0,0.0,3
39,lsoa_of_accident_location,str,0,0.0,27179
40,enhanced_severity_collision,int64,0,0.0,6
41,collision_injury_based,int64,0,0.0,2
42,collision_adjusted_severity_serious,float64,0,0.0,6557
43,collision_adjusted_severity_slight,float64,0,0.0,6557

In [40]:
# Short Data Quality Summary
column_summary.sort_values(
    by="Missing_Percentage",
    ascending=False
)

,Column,Data_Type,Missing_Count,Missing_Percentage,Unique_Values
0,collision_index,str,0,0.0,101525
1,collision_year,int64,0,0.0,1
2,collision_ref_no,str,0,0.0,101525
3,location_easting_osgr,float64,2,0.0,83236
4,location_northing_osgr,float64,2,0.0,83768
5,longitude,float64,2,0.0,88044
6,latitude,float64,2,0.0,82164
7,police_force,int64,0,0.0,44
8,collision_severity,int64,0,0.0,3
9,number_of_vehicles,int64,0,0.0,13
10,number_of_casualties,int64,0,0.0,21
11,date,str,0,0.0,365
12,day_of_week,int64,0,0.0,7
13,time,str,0,0.0,1440
14,local_authority_district,int64,0,0.0,1
15,local_authority_ons_district,str,0,0.0,351
16,local_authority_highway,str,0,0.0,208
17,local_authority_highway_current,str,0,0.0,208
18,first_road_class,int64,0,0.0,7
19,first_road_number,int64,0,0.0,3110
20,road_type,int64,0,0.0,6
21,speed_limit,int64,0,0.0,6
22,junction_detail_historic,int64,0,0.0,11
23,junction_detail,int64,0,0.0,8
24,junction_control,int64,0,0.0,6
25,second_road_class,int64,0,0.0,9
26,second_road_number,int64,0,0.0,2487
27,pedestrian_crossing_human_control_historic,int64,0,0.0,5
28,pedestrian_crossing_physical_facilities_historic,int64,0,0.0,8
29,pedestrian_crossing,int64,0,0.0,10
30,light_conditions,int64,0,0.0,6
31,weather_conditions,int64,0,0.0,9
32,road_surface_conditions,int64,0,0.0,7
33,special_conditions_at_site,int64,0,0.0,10
34,carriageway_hazards_historic,int64,0,0.0,8
35,carriageway_hazards,int64,0,0.0,14
36,urban_or_rural_area,int64,0,0.0,3
37,did_police_officer_attend_scene_of_accident,int64,0,0.0,3
38,trunk_road_flag,int64,0,0.0,3
39,lsoa_of_accident_location,str,0,0.0,27179
40,enhanced_severity_collision,int64,0,0.0,6
41,collision_injury_based,int64,0,0.0,2
42,collision_adjusted_severity_serious,float64,0,0.0,6557
43,collision_adjusted_severity_slight,float64,0,0.0,6557

In [41]:
# Check identifiers Uniqueness
print("Total records:", len(df))

print("Unique collision_index:", df["collision_index"].nunique())
print("Unique collision_ref_no:", df["collision_ref_no"].nunique())

print("\nDuplicate collision_index:",
      df["collision_index"].duplicated().sum())

print("Duplicate collision_ref_no:",
      df["collision_ref_no"].duplicated().sum())

Total records: 101525
Unique collision_index: 101525
Unique collision_ref_no: 101525

Duplicate collision_index: 0
Duplicate collision_ref_no: 0

In [42]:
# Check Numerical Variables for Zero Values
numeric_zero_summary = (
    (df[numerical_columns] == 0)
    .sum()
    .sort_values(ascending=False)
)

numeric_zero_summary

carriageway_hazards                                 91375
pedestrian_crossing                                 74538
collision_adjusted_severity_serious                 69042
second_road_number                                  59134
junction_detail                                     45333
first_road_number                                   41465
collision_adjusted_severity_slight                  26110
second_road_class                                   24886
collision_injury_based                              13677
carriageway_hazards_historic                        13225
special_conditions_at_site                          13171
pedestrian_crossing_human_control_historic          13092
pedestrian_crossing_physical_facilities_historic    10692
junction_detail_historic                             5411
location_easting_osgr                                   0
collision_year                                          0
longitude                                               0
location_northing_osgr                                  0
collision_severity                                      0
latitude                                                0
junction_control                                        0
speed_limit                                             0
road_type                                               0
number_of_vehicles                                      0
number_of_casualties                                    0
day_of_week                                             0
local_authority_district                                0
first_road_class                                        0
police_force                                            0
weather_conditions                                      0
light_conditions                                        0
road_surface_conditions                                 0
trunk_road_flag                                         0
did_police_officer_attend_scene_of_accident             0
urban_or_rural_area                                     0
enhanced_severity_collision                             0
dtype: int64

In [43]:
# Check Negative Values
negative_summary = (
    (df[numerical_columns] < 0)
    .sum()
    .sort_values(ascending=False)
)

negative_summary

local_authority_district                            101525
junction_detail_historic                             87871
special_conditions_at_site                           87858
pedestrian_crossing_human_control_historic           87852
carriageway_hazards_historic                         87852
pedestrian_crossing_physical_facilities_historic     87851
longitude                                            86359
junction_control                                     44487
second_road_number                                   25105
enhanced_severity_collision                          13677
trunk_road_flag                                       7108
junction_detail                                       6701
pedestrian_crossing                                   6527
carriageway_hazards                                   5346
road_surface_conditions                                634
second_road_class                                      171
light_conditions                                        16
first_road_class                                         6
first_road_number                                        6
collision_year                                           0
location_northing_osgr                                   0
location_easting_osgr                                    0
latitude                                                 0
police_force                                             0
number_of_vehicles                                       0
collision_severity                                       0
day_of_week                                              0
number_of_casualties                                     0
road_type                                                0
speed_limit                                              0
weather_conditions                                       0
urban_or_rural_area                                      0
did_police_officer_attend_scene_of_accident              0
collision_injury_based                                   0
collision_adjusted_severity_serious                      0
collision_adjusted_severity_slight                       0
dtype: int64

## 4. Initial Data Profile

Based on the initial inspection, the dataset contains collision-level records
with information covering:

- Collision identification
- Geographic location
- Police force
- Collision severity
- Vehicles and casualties
- Date and time
- Road characteristics
- Junction characteristics
- Pedestrian crossing information
- Lighting conditions
- Weather conditions
- Road surface conditions
- Environmental hazards
- Urban or rural classification
- Police attendance
- Trunk road information
- Additional severity indicators

Several variables are categorical codes rather than descriptive labels.
These variables require interpretation using the official DfT data definitions
before meaningful analysis is performed.

## 5. Variable Classification

### 🔑 Identification Variables

- `collision_index`
- `collision_ref_no`

### 📍 Geographic Variables

- `latitude`
- `longitude`
- `location_easting_osgr`
- `location_northing_osgr`
- `local_authority_district`
- `local_authority_ons_district`
- `local_authority_highway`
- `local_authority_highway_current`
- `lsoa_of_accident_location`

### 🚗 Collision Characteristics

- `collision_severity`
- `number_of_vehicles`
- `number_of_casualties`
- `enhanced_severity_collision`
- `collision_injury_based`
- `collision_adjusted_severity_serious`
- `collision_adjusted_severity_slight`

### 🛣️ Road Characteristics

- `first_road_class`
- `first_road_number`
- `road_type`
- `speed_limit`
- `second_road_class`
- `second_road_number`
- `junction_detail`
- `junction_control`

### 🌦️ Environmental Conditions

- `weather_conditions`
- `road_surface_conditions`
- `light_conditions`
- `special_conditions_at_site`
- `carriageway_hazards`

### 🚦 Pedestrian / Junction Information

- `pedestrian_crossing`
- `pedestrian_crossing_human_control_historic`
- `pedestrian_crossing_physical_facilities_historic`
- `junction_detail_historic`

### 🏙️ Location Classification

- `urban_or_rural_area`
- `trunk_road_flag`

### 👮 Police / Administrative Information

- `police_force`
- `did_police_officer_attend_scene_of_accident`

### 📅 Temporal Variables

- `collision_year`
- `date`
- `day_of_week`
- `time`

## 6. Initial Findings

The initial data inspection provides several important observations:

1. The dataset contains a large number of collision-level observations.
2. The dataset contains both numerical and categorical variables.
3. Several categorical variables are represented using numerical codes.
4. The dataset contains temporal variables such as date, day of week, and time.
5. Geographic coordinates are available for location-based analysis.
6. Road, weather, lighting, and surface-condition variables provide opportunities
   for environmental risk analysis.
7. Collision severity and casualty information provide opportunities to investigate
   factors associated with accident seriousness.
8. Missing-value patterns need to be investigated before performing statistical
   analysis.
9. Duplicate and identifier consistency should be checked before data cleaning.
10. Official DfT variable definitions are required before decoding categorical codes.

## 7. Data Understanding — Conclusion

The initial exploration confirms that the dataset is suitable for a comprehensive
Exploratory Data Analysis project.

It contains information across multiple dimensions including:

- Time
- Location
- Road characteristics
- Environmental conditions
- Collision characteristics
- Severity
- Vehicles
- Casualties

The next stage of the project will focus on assessing data quality in detail.

This will include:

- Missing-value analysis
- Duplicate analysis
- Invalid-value detection
- Data-type validation
- Categorical-code validation
- Outlier investigation
- Consistency checks

No data-cleaning transformations have been performed in this notebook.
The raw dataset has been preserved unchanged.